### ISSUE TITLE
Procurar exemplos de visualização de notícias

### ISSUE THREAD

**Issue by LBeghini** [Archeion-Project/ui#1]
Na tela inicial do projeto, haverá uma parte em que serão exibidas notícias sobre a entidade que contém os acervos.

Pesquisar alguns eemplos para poder dar base e ser desenhado no mockup.

**Comment by pedrovascojf** [comment]
![prefeituraJF](https://user-images.githubusercontent.com/77221541/129407643-10f82010-b434-4217-8535-111f270ee617.PNG)
![G1](https://user-images.githubusercontent.com/77221541/129407648-eb9c6ec8-54a3-4fea-8807-aee9c0d08f53.PNG)
![globo](https://user-images.githubusercontent.com/77221541/129407652-054b87cf-797f-423f-b0ab-330acf20e12e.PNG)
![HemerotecaDigital](https://user-images.githubusercontent.com/77221541/129407656-c51ef5f5-20ce-4bc8-9bf6-0ebe299d70b4.PNG)
![LegiaoDosHerois](https://user-images.githubusercontent.com/77221541/129407660-3e63f0f6-6c89-495f-9408-41425e184b54.PNG)
![NYT](https://user-images.githubusercontent.com/77221541/129407662-15ce7806-28f6-4fc6-8277-e6184e3eacea.PNG)
![Omelete](https://user-images.githubusercontent.com/77221541/129407663-07a914d9-4582-433f-bf3b-bdb5ed55e4b6.PNG)

**Comment by pedrovascojf** [comment]
1. [Globo.com](https://www.globo.com)
<img src="https://user-images.githubusercontent.com/77221541/129408656-2d9ad65a-1aa1-4b1f-b0bd-bbcaaf52edb2.PNG" width="400px">

2. [G1](https://g1.globo.com/?utm_source=globo.com&utm_medium=header)
<img src="https://user-images.githubusercontent.com/77221541/129408695-0b847c6b-f195-4dc7-9eed-83b3ed876e53.PNG" width="400px">

3. [Legião dos Heróis](https://www.legiaodosherois.com.br)
<img src="https://user-images.githubusercontent.com/77221541/129408753-e4b49205-ec1f-43dc-b860-8c5602f95ff5.PNG" width="400px">

4. [Omelete](https://www.omelete.com.br)
<img src="https://user-images.githubusercontent.com/77221541/129408820-9ed53b9c-3b10-45de-b168-f6414c37d7ba.PNG" width="400px">

5. [Hemeroteca Digital](https://bndigital.bn.gov.br/hemeroteca-digital/)
<img src="https://user-images.githubusercontent.com/77221541/129408868-f0a19a3f-bb63-44b3-8c43-6c3c75502512.PNG" width="400px">

6. [Prefeitura Juiz de Fora](https://www.pjf.mg.gov.br)
<img src="https://user-images.githubusercontent.com/77221541/129408938-2b04b90f-dcc4-41a4-92bf-388b22b293e1.PNG" width="400px">

7. [New York Times](https://www.nytimes.com)
<img src="https://user-images.githubusercontent.com/77221541/129409000-482bf643-5ec6-4dff-8d38-352067894e54.PNG" width="400px">

**Comment by LBeghini** [comment]
Pesquisei de forma genérica por "news website ideas" e obtive os seguintes resultados:

1. [Colorlib content is free. When you buy through links on our site, we may earn an affiliate commission. Learn More
18 Best News Website Designs For Inspiration 2021](https://colorlib.com/wp/best-news-website-design/)

2. [25 of the Best Examples of Home Pages](https://www.searchenginejournal.com/home-pages-examples/333251/#close)

> gostei muito do [Google Trends](https://trends.google.com/trends/?geo=BR)
